// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqrpxexodxqewvdpbauq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcnB4ZXhvZHhxZXd2ZHBiYXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5ODg0ODgsImV4cCI6MjA1MTU2NDQ4OH0.Po1_0q1xQDq2MLX6Rn1LLH5ic2TU2lmWUngnW1krcvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);